### ISSUE TITLE
Empty cells are ignored

### ISSUE THREAD

**Issue by sirio81** [pyexcel/pyexcel-ods3#17]
Hi, the get_data() method returns a list for each row.
The list contains only the values of non empty cells.
When parsing a table it may be necessary to know if a cell was empty.
I suggest to add and option the get_data() method so to include an empty string (or None value) for empty cells into the returned lists.

**Comment by chfw** [comment]
yes, the trailing empty cells are ignored: https://github.com/pyexcel/pyexcel-io/blob/dev/pyexcel_io/sheet.py#L88. but an option to toggle this behaviour can be added in pyexcel-io v0.6.0, the next release.

**Comment by sirio81** [comment]
Look forward for it!

**Comment by chfw** [comment]
pyexcel-io 0.6.0 was released. Please give it a go!

@kaittodesk  has help verify the fix.

https://github.com/pyexcel/pyexcel/issues/228
