### ISSUE TITLE
datetime (dates) from ODS can't be serialized by json...,

### ISSUE THREAD

**Issue by academay** [pyexcel/pyexcel-ods3#22]
I followed the readme.md example.

`json.dump(data)` failed, because one of the ODS sheet contained a **date value**.

Since dates are so popular in spreadsheets, I recommend:

 1. adding a comment in the readme, that this example fails with date values.
 2. Read datetime objects into a subclass (e.g. of  `datetime` or other modern date objects), with a default, serialize-able data representation / casting (string, numeric value, named-tuple).

e.g. 

(I have no clue what method is called by JSON.dumps on a non-built-in class)

```
# pseudo-code ahead:
class excel_datetime(datetime):
    def __repr__(self):
        fmt = self.default_date_format
        return strftime(self.data, fmt)
```

Hope this suggestion makes sense.

My aim is to make a default, minimal code data dumping of ods files.

This could be overridden by the user, on the constructor, e.g.

```
>>> from pyexcel_ods3 import get_data
>>> data = get_data("your_file.ods", date_representation='string', dateformat='yyyy-mm-dd')
>>> import json
>>> print(json.dumps(data))
# example of datetime formatted as string:
{"Sheet 1": [[1, '2019-12-31', 3], ]}
```
or
```
# example of datetime as decimal number:
{"Sheet 1": [[1, 1603093971.1975482, 3], ]}
```

thanks!

**Comment by chfw** [comment]
Please follow this [SO](https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable) post to do json dump.
