### ISSUE TITLE
Dictionaries instead of lists

### ISSUE THREAD

**Issue by sirio81** [pyexcel/pyexcel-ods3#26]
Hi, I think it's a common case to have a single table per sheet, with column labels (like in csv files).
This is not a bug report but more an enhancement discussion.
I wonder if it could be possible to have an argument like csv-style=True to pass to get_data() method.
This option assumes that all sheets have a single table and the first row contains column labels.
Doing so, instead of representing a sheet like a list of lists, it could be represented as a list of dictionaries, exactly how it happens with the csv.DictReader in the standard library.

The main advantage of using dictionaries is the possibility of altering the column order of the file, without the need to change the script code because cells are referenced by a key.

Let me know what you think about it please.
Thank you.

**Comment by chfw** [comment]
Hi, I suppose you are talking out this function here: http://docs.pyexcel.org/en/latest/generated/pyexcel.get_records.html#pyexcel.get_records

for the architecture here: http://docs.pyexcel.org/en/latest/architecture.html, pyexcel-io is designed to do read and write and pyexcel, the upper level library, would add a bit of 'sugar' to the api.

**Comment by chfw** [comment]
and here is an over view of all possibilities: http://docs.pyexcel.org/en/latest/capability.html

**Comment by sirio81** [comment]
Thank you for you reply.
Yes, pyexcel.get_records is exactly what I'm looking for.
Reading help(pyexcel.get_sheet) I found out how to ask for a specific sheet: sheet_name, otherwise it get the first sheet only.
get_book_dict is also pretty interesting but in my case this time.


I was confused by pyexcel-ods and pyexcel-ods3.
After reading the architecture I may be more :-D
BTW, correct me if I'm wrong, I can "import pyexcel" and manage ods files, without the need to import a specific library such as pyexcel-ods3 (ad I was doing till now).
pyexcel will take care of that right?

**Comment by chfw** [comment]
Here is the plugin guide: http://io.pyexcel.org/en/latest/#plugin-shopping-guide


pyexcel-ods and pyexcel-ods3, historically, they were made to support python 2 and python 3. But now as pyexcel supports python 3.6+ and pyexcel-ods supports python 3.6 too, the only difference is the underlying library(driver) is different and the license of the library is different.

In short, you need to use `pip` to install individually(or cherry pick the pyexcel plugins that you want to use per project per virtual environment)
