### ISSUE TITLE
Tries to call cell.split("\n") on datetime column

### ISSUE THREAD

**Issue by madduck** [pyexcel/pyexcel-ods3#31]
I am trying to save a `datetime` object to an ODS file, which produces:

```
  File "/home/madduck/.local/lib/python3.9/site-packages/pyexcel_ods/odsw.py", line 47, in write_cell
    lines = cell.split("\n")
AttributeError: 'datetime.datetime' object has no attribute 'split'
```

I could use `strftime`, but I don't want to store a string, but a timestamp. Am I doing something wrong?

**Comment by chfw** [comment]
please try use v0.6.1
