### ISSUE TITLE
Appending a line to a ods table without changing the rest

### ISSUE THREAD

**Issue by hajohoetger** [pyexcel/pyexcel-ods3#38]
Hi,
i'm not too confident to get the solution to my problem, but you'll never know if you don't try.

I have a table containing measured values. Column A contains a timestamp and Col B the measured value. Columns C to F contain various calculations as function of the measured values in Col B.

I want to append a new measurement periodically by script without changing the formulars in Col C-F.  Currently i managed to append only by reading the file, appending the line and writing it back.

Like this:
'''
#!/home/hajo/venvs/pyexcel-ods3/bin/python
import datetime
from pyexcel_ods3 import get_data
from pyexcel_ods3 import save_data

price = float(input("How much is the fish?\n: "))
data = get_data("fishprice.ods")
data["2024"].append([datetime.datetime.now(), price])
save_data("fishprice.ods", data)
'''

This script overwrites all the formulars in Col C-F with the respectively calculated values. But i want to keep the formulars and have only the timestamp and new measurement appended. Is this possible?
Best regards
HaJo

**Comment by chfw** [comment]
I think you are better off using ods libraries directory. pyexcel is made for information processing , not for editing like you would do using OpenOffice.
